language: node_js
node_js: stable
script:
  - yarn test-with-coverage
  - yarn build
before_script:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) download
after_success:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh)
deploy:
  provider: pages
  token: $github_token
  local_dir: public
  edge: true #opt in dpl v2
  on:
    branch: master
