language: node_js
node_js: stable
script:
  - yarn test-with-coverage
  - yarn build
deploy:
  provider: pages
  token: $github_token
  local_dir: public
  edge: true #opt in dpl v2
  on:
    branch: master
