language: node_js
node_js:
- stable
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn test
- yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$github_token"
  local_dir: build
  on:
    branch: master
notifications:
  webhooks: https://www.travisbuddy.com/
addons:
  browserstack:
    username: iancook3
    access_key:
      secure: ilhQLLuTpaHUfBJeuBnJt/VC3/RiN/VuSupYkz57XER3sRRhzNwVFoeODLXauBNsdqI608VobWE/sYf9fzO94DtijY0sBW2O8RVoRvb8nsdWr7kHHoSRVZR6k+4pRQVx0hpkYFPs68Cs0x0eN4tH8NFpzZcaE+rokBKYqzqVknM4LxhCxO8OVrQKaNYbBCHT34G+7HMNkzbjSIBbll5ILHcLgZCGyjOU44ZE8TV6BEbju5pPusrb9wbmBuZ+3OXHpQvuV6KJhYegsh0pTSgfUorq6bAMx0mhNO2aVnH1aKR+pPaXjb5hmNKcCJ6lP0sIMgDQOXQHBHrHJfR6hCkIKWudY1wE5Q8iABx0IQ/zJAopXlcLw1bGhXcSmGtycMSiNQuavSXZFPER74H0yITTYw4NLBgrNZRQPDVADHnmGietkkPkpd7jBslVuuHWumGNiXWg7ZeG/g7kT83otiLpEraErE+nan1TsORCM/Tact1jnRfQt7Fad0s7pEr/OXj3I6l4Ohu5+7Ryl0JjNMefvTi7gpkBOPBJVS0RwKyp/IoavyMlD1nurRvRvPcQ0S/G4+mklthUA/C3CpqsVkI+Qsf44Hj1nkE6s56uln9vBAc66jU+rl136gPB7TNYpjxSU/oyIpzdEMWP/uZg+5eDwajdKD0RoMKR/O0WPaqOHds=
