language: node_js
node_js:
- stable
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn test
- yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$github_token"
  local_dir: build
  on:
    branch: master
addons:
  browserstack:
    username: iancook3
    access_key:
      secure: GqiC2BSRuejpOMRA+loX7sEKRePwCyaG3EAG4eawXOyH4a4w7aNQu6sfVVUk8fuZMcRuon/MoEMCfxMS56wcWpVlcb/j3RFfUu7q24b9Y5ADXpnMSMf6gMdZ6ZL0Kxxn7p9BpgDigS3L45PdQwguBiqJLX6vrQUuf+Cs51HGOzNUWB5w1574e6ni0/V/IBH9HGj+bDMkxAqyNYec7ynpXmuS/MbZcL+5nGjElFKWWb2Fi727+H7nvUAoYpfAGfxOXNV7m/3j35l2Rddbnj2v4OgCcVQQ/0zlovWSu4mlOZz3SZzck1X2s2HsqQDG7Pj1mhlEMBzd93y8cj6trd6d96GzjdQTsc6Fsfyj00Eoknjn1d5Svlie+j6a1BIUSoqmx6EMo06bMJ+x29gYbxdQ5ieKzvnLdgLr+dWRU84HYSEM0fcKnR1kKMvhfIGOHkHwtCUS8vBqCbgPv0a0BTdcV6ebv97rO7i6SgU/5w4xRA6/o688xa2c+03Vaf0RykMMTP9QrzbMC1hDS8XRqLuLgLC5NHdsdGBdQtaCbZtc8OqhxhtqAuu0ijah1gBgI5Jm/oskn2iE7xUAnOGjyOy6hreNW9tarGPjjsJKkRn/CxSN4KuaQwkUuRS9UFwHzffWoX1FrdB3vUW/Wr5WkH2gcqFQnCFulumNqWXS/s+2es4=
