language: node_js
node_js:
- stable
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn test
- yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$github_token"
  local_dir: build
  on:
    branch: master
addons:
  browserstack:
    username: iancook3
    access_key:
      secure: hJjfUXxkWUaCVU0P34yekeoec/+G0lKEIPCwoKE2EeZbnXBWBgEuzeNGA5HF8F13WO7VvXmnwu8or8CgGul9G8m/esRhM9o18ZyseRGzbW78L0RDxR0LdXm9QiGzm89QjwNWX+zcT3L9WsQkZ7UlxsG75uYnl20NscDA7hFK2LWI5gj3LiFXiBJ/RcEy42EkSJCWQPNjpFAYlt7ci4eSeYw71T7pT8/APOV/locF+C2dHcdgjYPi4SzvV7vS88aIxrb0sRmVCmiZbGi9WNMNDClzV3+o+jMUBxwc4VJLx1mabWO46qLz6tqYfSnhY3uDXsHm+5sLLi0O0OSYg7Es9s3dhyqpKxHlRjc1VUjz3NHOIV8hpyNjAYTKerX2hXl3+88WzkianhbmJxhnnh9F0vbILfEqaCCX/2thDoWEKMudVUWOASug8Z+Hb5Oj2EzGIdSqtm67unt4LTmrQsYR6R1dEqqwCUd04vM/GgFL4MMo8HKcUDk/4C8NiuyfR/S+/9Lchti2Ox6zJ7lW8hiIihWAXNs+YP4FnqSnVTxraThfBu54jB69Lf7TLVlMAsA75UzukpDX7ksILMFWCEiL4X8bdVL5teP/Ix8ur78MZwOByRZUvZPX5qXsSn0TA0FLQsMjNN6Wvs0YjRJN92wwboSJhtOBQXmk76r7pjBGnnI=
